name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # You can change this to the branch you are working with

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx (optional but recommended for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the client Docker image
      - name: Build and push Docker image (client)
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-client:latest
        env:
          VITE_CURRENCY: ${{ secrets.VITE_CURRENCY }}

      # Step 5: Build and push the server Docker image
      - name: Build and push Docker image (server)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-server:latest
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SELLER_EMAIL: ${{ secrets.SELLER_EMAIL }}
          SELLER_PASSWORD: ${{ secrets.SELLER_PASSWORD }}
